# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: issue_analyzer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'issue_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14issue_analyzer.proto\x12\rissueanalyzer\")\n\x13\x41nalyzeIssueRequest\x12\x12\n\nissue_link\x18\x01 \x01(\t\"(\n\x14\x41nalyzeIssueResponse\x12\x10\n\x08response\x18\x01 \x01(\t2h\n\rIssueAnalyzer\x12W\n\x0c\x41nalyzeIssue\x12\".issueanalyzer.AnalyzeIssueRequest\x1a#.issueanalyzer.AnalyzeIssueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'issue_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEISSUEREQUEST']._serialized_start=39
  _globals['_ANALYZEISSUEREQUEST']._serialized_end=80
  _globals['_ANALYZEISSUERESPONSE']._serialized_start=82
  _globals['_ANALYZEISSUERESPONSE']._serialized_end=122
  _globals['_ISSUEANALYZER']._serialized_start=124
  _globals['_ISSUEANALYZER']._serialized_end=228
# @@protoc_insertion_point(module_scope)
